version: '3'

services:
  web:
    image: django
    container_name: django_run
    build: .
    restart: on-failure
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - .:/app
